#~ovn!
"""Models for coordinating power flow

Author:
    R Murali Krishnan
    
Date:
    10.12.2023
    
"""



from cdcm import *

import numpy as np
from numbers import Number
from scipy.optimize import Bounds, LinearConstraint, milp


class PowerGenerator(System):
    """Model of a power generating system"""
    def __init__(self, name: str, dt: Parameter, gen_rate: float, **kwargs) -> None:
        self.dt = dt
        self._generation_rate = gen_rate 
        super().__init__(name=name, **kwargs)

    def define_internal_nodes(self, **kwargs):

        power_generation = Parameter(
            name="power_generation",
            value=self._generation_rate,
            description="Power produced by the generator system"
        )

        energy_generated = Variable(name="energy_generated", value=0.0)

        @make_function(energy_generated)
        def calculate_energy_generates(r=power_generation, dt=self.dt):
            """Amount of energy generated by the power generator"""
            return r * dt

        return super().define_internal_nodes(**kwargs)
    

def make_power_generator(name: str, clock: System, generation_rate: Number, **kwargs):
    return PowerGenerator(name, clock.dt, generation_rate, **kwargs)


class PowerConsumer(System):
    """Model of a power consumer"""

    def __init__(self, name: str, dt: Parameter, power_request: Number, **kwargs) -> None:
        self.dt = dt
        self._power_request = power_request
        super().__init__(name=name, **kwargs)

    def define_internal_nodes(self, **kwargs):

        power_request = Parameter(
            name="power_request", 
            value=self._power_request,
            description="Power request to be fulfilled for fully functional system"
        )
        energy_request = Variable(name="energy_request", value=0.0)

        @make_function(energy_request)
        def calculate_energy_request(r=power_request, dt=self.dt):
            """Amount of energy requested"""
            return r * dt
        
        energy_supplied = Variable(name="energy_supplied", value=0.0)

        # 
        switch = Variable(name="switch", value=0.0)

        supply_decision = Variable(name="supply_decision", value=0.0)

        @make_function(energy_supplied)
        def calculate_energy_supply(r=energy_request, decision=supply_decision, sw=switch):
            """Amount of energy supplied"""
            return r * decision * sw

        return super().define_internal_nodes(**kwargs)
    
def make_power_consumer(name: str, clock: System, power_requested: Number, **kwargs):
    return PowerConsumer(name, clock.dt, power_requested, **kwargs)


class Distributor(System):
    """A power distribution system"""
    @property
    def compiled(self):
        return self._compiled
    
    @compiled.setter
    def compiled(self, val):
        self._compiled = val

    def __init__(self, 
                 name: str, 
                 **kwargs) -> None:
        self._suppliers = []
        self._consumers = []
        self.compiled = False
        super().__init__(name=name, add_internal_nodes=False, **kwargs)
    
    def __enter__(self) -> 'Distributor':
        return super().__enter__()
    
    def __exit__(self, typ, value, traceback):
        if not self.compiled:
            self._compile()
        return super().__exit__(typ, value, traceback)
    
    def _compile(self, alpha: Number=1):
        """Compile energy connection"""
        if self.compiled:
            err_msg = ("Attempting to re-compile connections in the ",
                       "energy distribution system. This is currently not supported!")
            raise RuntimeError(''.join(err_msg))
        else:
            available_energy = Variable(
                name="available_energy", 
                value=0.0
            )
            x_i = [s.energy_generated for s in self._suppliers]
            calc_sum = lambda *args: sum(args)
            fn_available_energy = Function(
                name="func_available_energy",
                parents=x_i,
                children=available_energy,
                func=calc_sum,
                description="Calculate the available energy"
            )

            # ncons = len(self._consumers)
            lambda_i, request_i = [], []
            for ncons, s in enumerate(self._consumers):
                lambda_i.append(s.priority)
                request_i.append(s.energy_request)

            to_array = lambda *args: np.array(args, dtype=np.float32)
            lambda_vector = Variable(name="lambda_vector", value=np.zeros(ncons + 1))
            fn_priority_vector = Function(
                name="cons_priority_vector",
                parents=lambda_i,
                children=lambda_vector,
                func=to_array
            )
            request_vector = Variable(name="request_vector", value=np.zeros(ncons + 1))
            fn_request_vector = Function(
                name="cons_request_vector",
                parents=request_i,
                children=request_vector,
                func=to_array
            )
            alpha = Parameter(name="alpha", value=alpha, track=False)
            decisions_vector = Variable(name="decisions_vector", value=np.zeros(ncons + 1))
            objective_vector = Variable(name="objective_vector", value=np.zeros(ncons + 1))
            @make_function(decisions_vector, objective_vector)
            def optimize_mil_program(Lam=lambda_vector, Alph=alpha, Req=request_vector, Avail=available_energy):
                """Optimize multi-integer linear program"""
                obj = -1.0 * (Lam + Alph * Req)
                bounds = Bounds(0, 1)
                constraints = LinearConstraint(Req, 0.0, Avail)
                res = milp(c=obj, constraints=constraints, 
                        integrality=np.ones_like(obj), 
                        bounds=bounds)
                return res.x, obj

            for idx, consumer in enumerate(self._consumers):
                consumer_idx = Parameter(name=f"{consumer.name}_idx", value=idx)

                func_set_consumer_decision = Function(
                    name=f"func_set_{consumer.name}_decision",
                    parents=(decisions_vector, consumer_idx,),
                    children=consumer.supply_decision,
                    func=lambda vec, idx: vec[idx],
                    description="Selector function for decision variable"
                )
            self.compiled = True

    
    def connect(self, system: System, priority=None):
        """Make a connection to"""
        if self.compiled:
            compiled_err_msg = ("Attempting to connect systems to an already compiled",
                                "energy distribution system. This is currently not supported!")
            raise RuntimeError(''.join(compiled_err_msg))
        else:
            if isinstance(system, PowerGenerator):
                self._suppliers.append(system)
            elif isinstance(system, PowerConsumer):
                self._consumers.append(system)
                priority = self._consumers.index(system) if priority is None else priority
                # add priority information to the system
                with system:
                    priority = Parameter(name="priority", value=priority)
            else:
                msg = ("Power distribution can connect to power generators or ",
                    "power consumers, recieved a bad connection request from",
                    f" << {system.absname} >>")
                raise TypeError(''.join(msg))